name: Docker-Build-Image

on:
  push:
    branches: ['main']

env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.run_number }}-${{ github.sha }}
  REGISTRY:  DockerHub
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Server_PASSWORD LOGIN
        # You may pin to the exact commit or the version.
        # uses: D3rHase/ssh-command-action@981832f056c539720824429fa91df009db0ee9cd
        uses: appleboy/ssh-action@master
        with:
          # hostname / IP of the server
          HOST: ${{ secrets.SERVER_IP }}
          # ssh port of the server
          PORT: 22 # optional, default is 22
          # user of the server
          USERNAME: root
          # private ssh key registered on the server
          PASSWORD: ${{ secrets.PASSWORD }}
          # command to be executed
          COMMAND: cd /root && ./run.sh

